# Generated by Django 3.2.5 on 2021-08-03 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('1', 'Dunyo'), ('2', "O'zbekiston"), ('3', 'Sport'), ('4', 'Texnologiya'), ('5', 'Ilm-fan'), ('6', "San'at"), ('7', 'Boshqa')], default='4', max_length=35)),
                ('region', models.CharField(choices=[('1', 'Andijon viloyati'), ('2', 'Buxoro viloyati'), ('3', "Farg'ona viloyati"), ('4', 'Jizzax viloyati'), ('5', 'Xorazm viloyati'), ('6', 'Namangan viloyati'), ('7', 'Navoiy viloyati'), ('8', 'Qashqadaryo'), ('9', "Qoraqalpog'iston Respublikasi"), ('10', 'Samarqand viloyati'), ('11', 'Sirdaryo viloyati'), ('12', 'Surxondaryo'), ('13', 'Toshkent viloyati'), ('14', 'Toshkent shahri')], default='14', max_length=35)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
